### ISSUE TITLE
Skip conda-meta check for python 2.7

### ISSUE THREAD

**Issue by mhw-at-yg** [JamesRamm/archook#24]
Recent addition `verify_conda_meta_dir()` uses f-strings which don't exist in python 2.7. This function can be skipped entirely for 2.7 as the problem it's reporting on doesn't apply.

~~~
(archook-py27-32) D:\code\public\archook\test>python simple-test-arcmap.py
========================================
Traceback (most recent call last):
  File "simple-test-arcmap.py", line 4, in <module>
    import archook
  File "d:\code\public\archook\archook\__init__.py", line 1, in <module>
    from .archook import locate_arcgis, get_arcpy
  File "d:\code\public\archook\archook\archook.py", line 57
    """)
      ^
SyntaxError: invalid syntax
~~~

**Comment by mhw-at-yg** [comment]
No good. Commit fb0c710 fixes py2 but breaks py3.
